<html>
  <section>
      <h1><span class="small block">Petit mémo sur</span>async/await</h1>
  </section>

  <section>
    <h1>Await</h1>
    <p>Toute promise peut être utilisée avec <code>await</code> :</p>
    <pre><code>"use strict";

const { promisify } = require('util');
  
const figlet = promisify(require('figlet'));

const title = await figlet('Title');
console.log(title);

const titles = await Promise.all([
  figlet('Hello'),
  figlet('world')
]);
titles.forEach(console.log);</code></pre>
    <p class="warning"><span><code>await</code> ne peut être utilisé que dans une fonction asynchrone.</span></p>
  </section>

  <section>
    <h1>Async</h1>
    <p>N'importe quelle fonction peut être déclarée asynchrone ; toute fonction asynchrone pourra utiliser <code>await</code> dans son corps.</p>
    <pre><code>async function maFonction() {}
const maFonction2 = async function() {};
const maFonction3 = async () => {};

uneFonctionACallback(async () => {}); // Ça, c'est tendu. Ça ne marchera que si `uneFonctionACallback` est prévue pour gérer async/await
</code></pre>
    <p class="advice"><span>Pour le point d'entrée, et plus précisément pour la "fonction asynchrone d'entrée", il peut être de bon ton de retourner une promise (le scope principal d'un fichier n'étant pas asynchrone, on ne peut pas y utiliser <code>await</code>).</span></p>
    <pre><code>"use strict";

async function start() {
  // ...
  return Promise.resolve();
}

start()
  .then(() => console.log('script terminé'));</code></pre>
  </section>

  <section>
    <h1>Attraper les erreurs</h1>
    <pre><code>function fetchSomething() {
  // throw new Error('argh');
  // return new Promise((resolve, reject) => reject('argh'));
}

async function doSomething() {
  try {
    const something = await fetchSomething();
  } catch (error) {
    console.error(error);
  }
}</code></pre>
  </section>
</html>